### ISSUE TITLE
Unable to preview

### ISSUE THREAD

**Issue by ChantalLavigne** [HPDCollaborative/builder23review#10]
A navigating tab with codes appears when I tried to preview the HPD (Palmex)
![image](https://user-images.githubusercontent.com/107648303/175038099-9b1bbbd5-fd45-4a62-81fb-237ba3b4a6b5.png)

**Comment by Millali** [comment]
@secondmanveran 

Hi Vince, 

This is the record Chantal is trying to preview: 

https://stage.hpd-collaborative.org/actions/builder/5578/record


Milla

**Comment by secondmanveran** [comment]
Perhaps you might try fixing some of the 26 compliance issues present on the record before trying to preview it?

**Comment by secondmanveran** [comment]
@Millali 

Yeah I think maybe there needs to be all green on Nested, Substance, Materials before a preview can be generated. We're simply writing too many messages to the pdf at this point and with so many missing elements when a record is updated it's going to be impossible to catch all the possible errors in time for the launch.
