### ISSUE TITLE
Nested HPD not upgrading to 2.3

### ISSUE THREAD

**Issue by ChantalLavigne** [HPDCollaborative/builder23review#14]
when I click on the "upgrade to 2.3", a "Heads Up!" window appears.  Then, I click on "Upgrade" and nothing appens.
![image](https://user-images.githubusercontent.com/107648303/175042690-527a1b32-6958-418b-b562-c784043a4638.png)

**Comment by Millali** [comment]
Hi  Vince @secondmanveran, 

This is the record Chantal is working on. I also tried to update the record and nothing happens when I click the updgrade button. 

https://stage.hpd-collaborative.org/actions/builder/product/454

Best, 

Milla

**Comment by secondmanveran** [comment]
@Millali @wdvittori @ChantalLavigne 

This turned out to be nothing more than a typo and only effected records that were previously published.

**Comment by wdvittori** [comment]
thank you, Vince and Milla, for chasing this one down and checking it out thoroughly!
