### ISSUE TITLE
Special Condition Missing from Substances

### ISSUE THREAD

**Issue by ChantalLavigne** [HPDCollaborative/builder23review#15]
I understand this does not apply to materials, but it does to substances.

In v2.2, additional question/information must be added for spectial conditions. Example:
![image](https://user-images.githubusercontent.com/107648303/175077201-3af433bd-ddf4-4b7b-9019-cb633cc5e09b.png)

In is my understanding that this is still valid in v2.3, but will show up differently in the pdf. I don't see where I can enter such information in the staging HPD builder. No Special Condition indication that I can find, except "Utilize the below checkboxes only if you'r certain the substance doesn't qualify as a Material Data Element". Nothing appends when I check the "no CAS RN box. No additional menu to enter the additional information needed for Special Condition substances.
![image](https://user-images.githubusercontent.com/107648303/175077877-2ab1e655-cef3-4cf3-9b7a-199cd9b45676.png)

**Comment by secondmanveran** [comment]
@ChantalLavigne 

No you've misunderstood.

There are no longer any Special Conditions for substances or nested materials (formerly materials). Special Conditions now exist as their own entity, what we've named a Material.

So ... Nested Materials now hold both substances and materials (special conditions)

Hope that helps

**Comment by Millali** [comment]
@ChantalLavigne, 

Special Conditions are now entered as materials (Which is what they are) and we have combined the substance and materials fields. See attached the circled area where you will be able to add SC. 

That being said, as I mentioned in the guidelines, SC are not ready for testing yet. They are still updates to implement. 



![screencapture-stage-hpd-collaborative-org-actions-builder-7265-record-2022-06-22-14_06_55](https://user-images.githubusercontent.com/34175076/175106978-07eaa3fa-5bf7-44e4-a6b3-43f4cc14b616.png)

**Comment by ChantalLavigne** [comment]
@Millali 
@secondmanveran 
I found it. No testing. got it!  Thanks!
