### ISSUE TITLE
Display the word "Withdraw" in the records page. 

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder23review#16]
@secondmanveran, 

Hi Vince,

Please display the full word for the withdrawal button on the records page. An X is not a clear indicator that this is where you withdraw records. Also, what is the eye icon supposed to do? I can't click it. 

https://stage.hpd-collaborative.org/actions/builder/product/4875 

Thanks, 

Milla

**Comment by secondmanveran** [comment]
This isn't possible, these are SVG icons that have no way to add words to them.

We may be able to add a tooltip, I'll check into it, but either way this is cosmetic.

**Comment by Millali** [comment]
Hi @secondmanveran, 

Please add a tooltip or any other way to indicate users how to withdraw an HPD. It is not obvious, and I just got two inquiries about it today.

Thanks!

Milla
