### ISSUE TITLE
MasterFormat Classification Not Pulling Through 

### ISSUE THREAD

**Issue by alyperez106** [HPDCollaborative/builder23review#17]
CSI Division is not carrying over when updating both nested and basic HPDs to v2.3 

![image](https://user-images.githubusercontent.com/108025968/175118056-16df5cd6-a21b-4c6e-a57b-b6c309821560.png)

**Comment by Millali** [comment]
Hi Aly, 

Could you please send me the name of the HPD? This is normal for old records that were published prior to the CSI Masterformat searchbox implementation. 

Thanks!

Milla

**Comment by secondmanveran** [comment]
@Millali 

Have you verified this issue?

**Comment by Millali** [comment]
@secondmanveran not yet!

**Comment by secondmanveran** [comment]
This was created 2 weeks ago and has no response from the user.

I'm gonna close this and we can revisit if someone else reports it.
