### ISSUE TITLE
Accessories: Installation Accessory requiring "Other" entry

### ISSUE THREAD

**Issue by Elixir-Tara** [HPDCollaborative/builder23review#19]
When entering an Accessory, if the Accessory Type "Installation Accessory" is selected, the box "Enter Other Accessory Type" appears (and is required to save). However, when Accessory Type "Other (Enter Type)" is selected, no such box appears. All of the other Accessory Type choices seem to be working properly.

**Comment by Millali** [comment]
Thanks @Elixir-Tara 

@secondmanveran this has been reproduced. Please fix.
