### ISSUE TITLE
Unable to edit the Certification name

### ISSUE THREAD

**Issue by ChantalLavigne** [HPDCollaborative/builder23review#26]
Hi,
Perhaps this is how you want it, but in the past, we could edit the Name of Certificate of Compliance.  In v.2.3, this is not possible.  It was useful when the certificate you wanted to add was not in the list.  For example, if a program operator was not listed in the EPDs.
![image](https://user-images.githubusercontent.com/107648303/177561415-6c5f0eef-48ce-4370-ab8a-ed5e26026194.png)

**Comment by secondmanveran** [comment]
@ChantalLavigne 

You are required to use the Certification search palette to fill the name (and other background info) or use one of the 3 check boxes if your cert isn't found.

I'll leave this open for the moment so @Millali can weigh in, but this is how I was instructed to program it, so I'm pretty sure.

**Comment by Millali** [comment]
@secondmanveran that's right, users should select from the given options. 

Vince, how can we add new options to the lists? 

Milla

**Comment by secondmanveran** [comment]
@Millali 

We can't right now until we move the certs over to our database.

After that we'll have an admin form to add new certs or edit/delete existing ones.

**Comment by Millali** [comment]
Ok, thank you!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
