### ISSUE TITLE
Undisclosed substance CAS shown in HPD builder

### ISSUE THREAD

**Issue by ChantalLavigne** [HPDCollaborative/builder23review#27]
@secondmanveran 
All the “undisclosed” substances in the HPD prepared by Vertima need to have the box “I do not want to disclose this substance’s CAS RN in the HPD builder” checked by default before the builder v2.3 goes live.  In the stage builder, this box is not checked. 
 
![image](https://user-images.githubusercontent.com/107648303/177564427-691c9989-739e-4195-ad78-eab574771585.png)

Thanks.

**Comment by secondmanveran** [comment]
@ChantalLavigne 

Once again ... this is data that's several years old. Your data in the live builder will not be altered, so I'd suggest making certain these are checked now on the live server.

The one thing you'll have to do after upgrading is re-address any Nested Materials that were previously set as an alternate. Any data structure that allows alternates (Nested Material, Substance, Material) MUST have a parent item of the same type attached. 

Existing Materials that are being upgraded to Nested Materials will not have this parent element, so its alternate state is reset to false so it can be corrected in editing.

**Comment by ChantalLavigne** [comment]
@secondmanveran 
This double option present in v2.3: 1) Do not disclose CAS RN on the HPD; 2) Do not disclose CAS RN in the builder, are not separate in the actual v2.2 builder.  I cannot go in the live server to check a box that does not yet exist.  All "undisclosed" substance have been checked "Do not disclose the name of this substance on the HPD" and "I don't want to disclose this substances CAS RN".  Thus, this information shall not appear when the builder is updated to v2.3.

Menu to enter substance to be undisclosed in the v2.2 builder (or what you call the live server)
![image](https://user-images.githubusercontent.com/107648303/177584101-aba16867-4cda-494f-8a15-ef867fa24c3d.png)

Hope this makes sense to you.
Thanks!

**Comment by secondmanveran** [comment]
@ChantalLavigne 

These checkboxes are exactly the same, the wording has been changed to more accurately reflect what they do, but they are the same as the current builder. The difference in layout is simply that we moved the casrn lookup to the top so now those checkboxes are closer together.

Just because the wording is changed slightly doesn't mean the functionality has changed.

```
v2.2: Do not disclose the name of this substance on the HPD 
v2.3: Do not disclose the name and CAS RN of this substance on the HPD

exact same functionality
```

same with the other box:

```
v2.2: I do not want to disclose this substance's CAS RN #.
v2.3: I do not want to disclose this substance's CAS RN in the HPD Builder.

exact same functionality
```

I hope this makes it clear for you.

**Comment by secondmanveran** [comment]
@ChantalLavigne 

It's in the same state that is was in when it was imported 4 years ago. Barring any changes made during development and testing. 

We don't go through and change things in client accounts, that only ever really happens when you guys come in to test. 

We have our own account which we use for testing so we don't pay any attention to client accounts. 

If you're trying to test security features, you should do that by creating an entirely new record, there's no guarantee that existing stage records have the data needed to test security.

Thanks

**Comment by ChantalLavigne** [comment]
@secondmanveran 
@Millali

Ok, there is two points: 1) making sure HPD prepared in v2.2 and prior with undisclosed substances remain as such. In other words, for undisclosed substances, the CASRN and substance name should not be seen in the builder and the HPD. 2) testing the security features in v2.3 in the staging HPD.

For the first point, I checked the 3 client accounts that are in the staging builder which have confidential data to see if everything that was market as confidential at the time would remain during the update.  Even if this is old data, for undisclosed substances, both boxes were checked (Do not disclose CASRN in builder + Do not disclose CASRN and substance name in HPD). What was not always done is renaming the substance to make sure you cannot see the confidential substance name in the builder.  I wanted to make sure that when the builder goes live to 2.3, all confidential information in our client account remain as such. In other words, for undisclosed substances, the CASRN and substance name should not be seen in the builder and the HPD.  That being said, if you have this under control.  I have nothing further to add.

Regarding the second point, I tried creating a new record in the staging builder, but since I can't add substances, I can't test the "security features".

Thanks
Chantal

**Comment by Millali** [comment]
@ChantalLavigne 

I will be testing your records over the weekend to make sure the confidential information is protected both in the Builder and in the HPD. IF you can send me a list of products that you know needs to be checked, it will help me a lot so that I am sure to cover them all. 

Milla
