### ISSUE TITLE
Cannot add substance to Basic Inventory

### ISSUE THREAD

**Issue by vanduima** [HPDCollaborative/builder23review#29]
When adding a new substance to a basic inventory, it doesn't save and it turns the "Product:" text red indicating that is the issue.  However, since it is a basic inventory, I cannot edit this field to make sure something is added.  You can see the steps on this loom: https://www.loom.com/share/2dc4ad0a63724c4aa2cf9afbae2cf47a 

Chrome Version 103.0.5060.114 (tested on safari too)
MacOS Monterey version 12.3.1

**Comment by vanduima** [comment]
This was additionally tested for materials (special conditions) and doesn't work for materials either.

**Comment by vanduima** [comment]
Here is the console log for this error:
VM1358:1 
 POST https://stage.hpd-collaborative.org/actions/builder/substances 422
(anonymous)	@	VM1358:1
(anonymous)	@	xhr.js:187
K	@	xhr.js:13
ur	@	dispatchRequest.js:53
Promise.then (async)		
C.request	@	Axios.js:88
C.<computed>	@	Axios.js:140
(anonymous)	@	bind.js:9
ic	@	actions.js:210
(anonymous)	@	vuex.esm.js:851
v.dispatch	@	vuex.esm.js:516
dispatch	@	vuex.esm.js:406
r.<computed>	@	vuex.esm.js:1064
saveSubstance	@	SubstanceForm.vue:482
click	@	SubstanceForm.vue?vu…=template&lang.js:1
qe	@	vue.esm.js:1872
r	@	vue.esm.js:2197
Hf.a._wrapper	@	vue.esm.js:7609

<img width="612" alt="image" src="https://user-images.githubusercontent.com/108848653/177687394-f56439a0-5d4f-42a4-bf06-a5e505c6d10e.png">

**Comment by Millali** [comment]
Hi @vanduima is this Matt? 

Can you do what I show in the video below and let me know if this works? 

https://www.loom.com/share/77106bb3b4354b89b01edf94f44f414b

Thanks,

Milla

**Comment by Millali** [comment]
@secondmanveran 
Vince, please take a look at this. It is happening on my end as well. This is what I get in telescope: 

https://stage.hpd-collaborative.org/admin/telescope/logs/96b8ce10-bdd7-4f40-87d1-8a3240658d35

Milla

**Comment by Millali** [comment]
@secondmanveran 

The user needs to be communicated that they need to select the threshold in order to save substances. Or any other action they need to do to be able to perform other functions. We can't just highlight the product name without any messages because they won't know what to do. 

Milla

**Comment by secondmanveran** [comment]
This should be working now, the `product.id` was not being set to the `form.material_id` if the substance is a product. Thats corrected.

**Comment by Millali** [comment]
Great. I was able to add a substance. 

@vanduima are you able to add substances to Basic Inventory?

**Comment by Millali** [comment]
@secondmanveran 
I still can add substances but was unable to add materials.

This is the record: 
 https://stage.hpd-collaborative.org/actions/builder/7284/record

This is the feedback in telescope: 
https://stage.hpd-collaborative.org/admin/telescope/logs/96b9a511-1c38-4fdd-9593-71704256dfe2

Milla

**Comment by secondmanveran** [comment]
@Millali 

Once again, that's just a deprecation notice, not an error.

This should be resolved with the latest push.

**Comment by Millali** [comment]
@secondmanveran thank you Vince
