### ISSUE TITLE
Wrong text in PDF summary for Basic Inventory

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder23review#30]
Hi Vince, @secondmanveran 
[2_Test_delete_product.pdf](https://github.com/HPDCollaborative/builder23review/files/9068097/2_Test_delete_product.pdf)
[2_Test_delete_product.pdf](https://github.com/HPDCollaborative/builder23review/files/9068098/2_Test_delete_product.pdf)

I am pretty sure this was reported and fixed already but for some reason is showing up again. It is on the PDF of Basic Inventory. See attached highlighted text, it should be "PRODUCT" Instead of "MATERIAL"

Thanks!

Milla

**Comment by secondmanveran** [comment]
@Millali 

Basic inventory PDFs have always begun with Material not Product, has that changed?

**Comment by Millali** [comment]
@secondmanveran I understand it has been like that, but it is wrong, we need to fix it. There are no materials in Basic Inventories. Also, Materials now refer to the Material Element, so having Material here does not really make sense. 

Here is the format PDF approved by the Technical Committee, it reads Product.  

https://www.hpd-collaborative.org/wp-content/uploads/2022/04/HPDC_FormTemplate_2.3_BASIC_PRODUCT_03.14.22_WithTPVLogo.pdf

Thanks!

Milla
