### ISSUE TITLE
Unable to save substance

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder23review#33]
Hi @secondmanveran 

I don't seem to be able to save substances

Here is a nested record: 
https://builder.hpd-collaborative.org/actions/builder/14876/record

Here is telescope:
https://builder.hpd-collaborative.org/admin/telescope/exceptions/96bfc261-ce35-477f-9785-7630e52ee399

Here is  basic record:
https://builder.hpd-collaborative.org/actions/builder/15224/record
https://builder.hpd-collaborative.org/admin/telescope/exceptions/96bfc34a-1e0b-444c-8814-b81a215b7496

Milla

**Comment by secondmanveran** [comment]
@Millali 

Added Carbon Black to 14876 with no issues, I did receive the Form Specific Hazards dialog.

Added Fast Blue to 15224 with no issues.

Looks like this is resolved

**Comment by wdvittori** [comment]
There is also an interesting time stamp on the screening, that I noticed.  8:25 PM today - no timezone noted.   I setup the record around 1:25 PDT.
