### ISSUE TITLE
CSI Masterformat search not working

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder23review#34]
Hi Vince @secondmanveran, 

Search does not seem to be working for the CSI Masterformat. When I search nothing comes up. 

Here is the telescope: 
https://builder.hpd-collaborative.org/admin/telescope/exceptions/96bfc61e-71e0-4d3a-a3ba-e5c825f3a46a

Also, there is a typo in the text below, changes "Titiles" to "Titles" 

Below you can search the CSI MasterFormat® Numbers and Titiles for terms that apply to your product.

**Comment by secondmanveran** [comment]
This is resolved
