### ISSUE TITLE
Adding Approve preparer/verifier Name

### ISSUE THREAD

**Issue by ChantalLavigne** [HPDCollaborative/builder23review#4]
Unless this button appears after the "Has compliance Issues" warming is removed, the button to add the name of the HPD preparer and/or verifier, such as Vertima, does not seems to be there.
![Preparer_Verifier button](https://user-images.githubusercontent.com/107648303/174398696-a4b6dfec-6b9e-479c-8662-0e7b63746a93.PNG)

**Comment by secondmanveran** [comment]
@ChantalLavigne 

This functionality has not changed. The user logged in must be the preparer or verifier for the record they are viewing in order to see those buttons.

**Comment by ChantalLavigne** [comment]
Vertima is a preparer and verifier.  That is why I ask.  Perhaps this "button" will be shown when the update in done in our "real" account. Thanks!

**Comment by secondmanveran** [comment]
I understand that, are you looking at a record that is for a company (other than yours) that you are a consultant for?

**Comment by Millali** [comment]
@secondmanveran , 

Currently, in the Builder verifiers and preparers can see the buttons anytime in the process. Please see the record below: 

https://builder.hpd-collaborative.org/actions/builder/10359/record

I was trying to add verifier and preparer rights to some companies to test this, and I am getting the error on the screenshot attached. 
![Uploading screencapture-stage-hpd-collaborative-org-companies-612-credentials-2022-06-22-13_59_50.png…]()


Best, 

Milla

**Comment by secondmanveran** [comment]
@Millali 

No they should not see them unless they are a consultant for the company of the product. Otherwise any verifier or preparer could simply verify or prepare hither and yon. 

I'm not a consultant for anyone and I can see the buttons because I'm a super admin. But normal consultants (non-super_admin verifiers and preparers) should only see these buttons if they are a member of a verifier/preparer company, and an authorized consultant for the company of the product.

**Comment by ChantalLavigne** [comment]
@Millali 
@secondmanveran 
I looked at one of our client account and cannot see this button. Yes, we are official HPD preparer/verifier.
![image](https://user-images.githubusercontent.com/107648303/175129831-4f35836a-5ea1-41ae-8051-c766788f466e.png)

**Comment by secondmanveran** [comment]
This was happening because Vertima was not registered as a third party on the stage. There was one other issue, but that's why @ChantalLavigne couldn't see the buttons.
