### ISSUE TITLE
Delete product button not working

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder23review#6]
Hi Vince, 

When I click the  "Delete Product" button, nothing happens. I didn't find anything in Telescope. This is the record I am working on: 

https://stage.hpd-collaborative.org/actions/builder/product/5043

Thanks!

Milla

**Comment by Millali** [comment]
I tried deleting the product before adding the records, and it doesn't work. Please test. Here is another example: 

https://stage.hpd-collaborative.org/actions/builder/product/5045

Milla

**Comment by secondmanveran** [comment]
@Millali 

Roger that, will mark as a bug.

**Comment by secondmanveran** [comment]
Pushing and closing this now
