### ISSUE TITLE
Removed requirement for "Expiry Date" 

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder23review#8]
Hi Vince, 

Would you please remove the "issue' for the expiry date requirement when the manufacturer selects either of the three VOC Emissions-checkboxes in the certifications section?  Since any of these three options are self-statements made by the manufacturer, there isn't really an expiry date for this, and the field needs to be left empty. 

Here is n example record displaying the issue in the certification section: 

https://stage.hpd-collaborative.org/actions/builder/7265/record

Thanks!

Milla

**Comment by secondmanveran** [comment]
@Millali 

Not sure what you mean, expiry date is never a required field.

**Comment by Millali** [comment]
@secondmanveran, please open the record and go to the certifications section to see the red issue showing up. 

Milla

**Comment by secondmanveran** [comment]
@Millali 

You didn't reference this as a Compliance Check problem, I thought you were referring to the form field.
