### ISSUE TITLE
Fix spacing in PDF -  certifications and compliance section

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder23review#9]
Could you fix the spacing a little in the PDF format to allow the certification validity dates fields to fit in one line? This is on the Certification and Compliance section. 

Look at the example HPD below, the issue date is not in one line and it doesn't look right. 
https://stage.hpd-collaborative.org/actions/builder/preview/7265/draft

**Comment by secondmanveran** [comment]
@Millali 

This is cosmetic and can be addressed after other items are fixed.
